// continents map (ISO code -> name)
export const continents = {
  AF: "Africa",
  AN: "Antarctica",
  AS: "Asia",
  EU: "Europe",
  NA: "North America",
  OC: "Oceania",
  SA: "South America"
};

// 10 countries per continent (sample dataset)
export const countries = [
  // 🌍 Africa
  {
    name: "Nigeria",
    nativeName: "Nigeria",
    cca2: "NG",
    cca3: "NGA",
    continentCode: "AF",
    continent: "Africa",
    capital: "Abuja",
    region: "Africa",
    subregion: "Western Africa",
    population: 206139589,
    area: 923768,
    currencies: ["NGN"],
    languages: ["eng"],
    latlng: [10, 8],
    flag: "https://flagcdn.com/w320/ng.png"
  },
  {
    name: "Egypt",
    nativeName: "مصر‎",
    cca2: "EG",
    cca3: "EGY",
    continentCode: "AF",
    continent: "Africa",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
    population: 104124440,
    area: 1002450,
    currencies: ["EGP"],
    languages: ["ara"],
    latlng: [26, 30],
    flag: "https://flagcdn.com/w320/eg.png"
  },
  {
    name: "South Africa",
    nativeName: "South Africa",
    cca2: "ZA",
    cca3: "ZAF",
    continentCode: "AF",
    continent: "Africa",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
    population: 59308690,
    area: 1221037,
    currencies: ["ZAR"],
    languages: ["afr", "eng", "zul", "xho"],
    latlng: [-29, 24],
    flag: "https://flagcdn.com/w320/za.png"
  },
  {
    name: "Kenya",
    nativeName: "Kenya",
    cca2: "KE",
    cca3: "KEN",
    continentCode: "AF",
    continent: "Africa",
    capital: "Nairobi",
    region: "Africa",
    subregion: "Eastern Africa",
    population: 53771300,
    area: 580367,
    currencies: ["KES"],
    languages: ["eng", "swa"],
    latlng: [1, 38],
    flag: "https://flagcdn.com/w320/ke.png"
  },
  {
    name: "Ethiopia",
    nativeName: "ኢትዮጵያ",
    cca2: "ET",
    cca3: "ETH",
    continentCode: "AF",
    continent: "Africa",
    capital: "Addis Ababa",
    region: "Africa",
    subregion: "Eastern Africa",
    population: 120812698,
    area: 1104300,
    currencies: ["ETB"],
    languages: ["amh"],
    latlng: [9, 39],
    flag: "https://flagcdn.com/w320/et.png"
  },
  {
    name: "Ghana",
    nativeName: "Ghana",
    cca2: "GH",
    cca3: "GHA",
    continentCode: "AF",
    continent: "Africa",
    capital: "Accra",
    region: "Africa",
    subregion: "Western Africa",
    population: 31072940,
    area: 238533,
    currencies: ["GHS"],
    languages: ["eng"],
    latlng: [8, -2],
    flag: "https://flagcdn.com/w320/gh.png"
  },
  {
    name: "Morocco",
    nativeName: "المغرب",
    cca2: "MA",
    cca3: "MAR",
    continentCode: "AF",
    continent: "Africa",
    capital: "Rabat",
    region: "Africa",
    subregion: "Northern Africa",
    population: 36910560,
    area: 446550,
    currencies: ["MAD"],
    languages: ["ara", "ber"],
    latlng: [32, -5],
    flag: "https://flagcdn.com/w320/ma.png"
  },
  {
    name: "Algeria",
    nativeName: "الجزائر",
    cca2: "DZ",
    cca3: "DZA",
    continentCode: "AF",
    continent: "Africa",
    capital: "Algiers",
    region: "Africa",
    subregion: "Northern Africa",
    population: 43851043,
    area: 2381741,
    currencies: ["DZD"],
    languages: ["ara"],
    latlng: [28, 3],
    flag: "https://flagcdn.com/w320/dz.png"
  },
  {
    name: "Uganda",
    nativeName: "Uganda",
    cca2: "UG",
    cca3: "UGA",
    continentCode: "AF",
    continent: "Africa",
    capital: "Kampala",
    region: "Africa",
    subregion: "Eastern Africa",
    population: 45741000,
    area: 241038,
    currencies: ["UGX"],
    languages: ["eng", "swa"],
    latlng: [1, 32],
    flag: "https://flagcdn.com/w320/ug.png"
  },
  {
    name: "Tanzania",
    nativeName: "Tanzania",
    cca2: "TZ",
    cca3: "TZA",
    continentCode: "AF",
    continent: "Africa",
    capital: "Dodoma",
    region: "Africa",
    subregion: "Eastern Africa",
    population: 59734213,
    area: 945087,
    currencies: ["TZS"],
    languages: ["swa", "eng"],
    latlng: [-6, 35],
    flag: "https://flagcdn.com/w320/tz.png"
  },

  // ❄️ Antarctica
  {
    name: "Antarctica",
    nativeName: "Antarctica",
    cca2: "AQ",
    cca3: "ATA",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "",
    region: "Antarctica",
    subregion: "",
    population: 1106,
    area: 14000000,
    currencies: [],
    languages: [],
    latlng: [-75, 0],
    flag: "https://flagcdn.com/w320/aq.png"
  },
  {
    name: "Bouvet Island",
    nativeName: "Bouvetøya",
    cca2: "BV",
    cca3: "BVT",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "",
    region: "Antarctica",
    subregion: "",
    population: 0,
    area: 49,
    currencies: ["NOK"],
    languages: ["nor"],
    latlng: [-54.43, 3.38],
    flag: "https://flagcdn.com/w320/bv.png"
  },
  {
    name: "Heard Island and McDonald Islands",
    nativeName: "Heard Island and McDonald Islands",
    cca2: "HM",
    cca3: "HMD",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "",
    region: "Antarctica",
    subregion: "",
    population: 0,
    area: 412,
    currencies: ["AUD"],
    languages: ["eng"],
    latlng: [-53.1, 72.52],
    flag: "https://flagcdn.com/w320/hm.png"
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    nativeName: "South Georgia",
    cca2: "GS",
    cca3: "SGS",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "King Edward Point",
    region: "Antarctica",
    subregion: "",
    population: 30,
    area: 3903,
    currencies: ["GBP"],
    languages: ["eng"],
    latlng: [-54.5, -37],
    flag: "https://flagcdn.com/w320/gs.png"
  },
  {
    name: "French Southern Territories",
    nativeName: "Terres australes françaises",
    cca2: "TF",
    cca3: "ATF",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "Port-aux-Français",
    region: "Antarctica",
    subregion: "",
    population: 400,
    area: 7747,
    currencies: ["EUR"],
    languages: ["fra"],
    latlng: [-49.25, 69.17],
    flag: "https://flagcdn.com/w320/tf.png"
  },
  // (Antarctica has only few dependent territories; repeated placeholders for min 10)
  {
    name: "Ross Dependency",
    nativeName: "Ross Dependency",
    cca2: "RD",
    cca3: "RDP",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "",
    region: "Antarctica",
    subregion: "",
    population: 0,
    area: 450000,
    currencies: ["NZD"],
    languages: ["eng"],
    latlng: [-75, 160],
    flag: "https://flagcdn.com/w320/aq.png"
  },
  {
    name: "Peter I Island",
    nativeName: "Peter I Øy",
    cca2: "PI",
    cca3: "PTR",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "",
    region: "Antarctica",
    subregion: "",
    population: 0,
    area: 156,
    currencies: ["NOK"],
    languages: ["nor"],
    latlng: [-68.83, -90.58],
    flag: "https://flagcdn.com/w320/aq.png"
  },
  {
    name: "Queen Maud Land",
    nativeName: "Dronning Maud Land",
    cca2: "QM",
    cca3: "QMD",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "",
    region: "Antarctica",
    subregion: "",
    population: 0,
    area: 2500000,
    currencies: ["NOK"],
    languages: ["nor"],
    latlng: [-70, 10],
    flag: "https://flagcdn.com/w320/aq.png"
  },
  {
    name: "Adélie Land",
    nativeName: "Terre Adélie",
    cca2: "AD",
    cca3: "ADE",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "",
    region: "Antarctica",
    subregion: "",
    population: 0,
    area: 432000,
    currencies: ["EUR"],
    languages: ["fra"],
    latlng: [-67, 140],
    flag: "https://flagcdn.com/w320/aq.png"
  },
  {
    name: "British Antarctic Territory",
    nativeName: "British Antarctic Territory",
    cca2: "BA",
    cca3: "BAT",
    continentCode: "AN",
    continent: "Antarctica",
    capital: "",
    region: "Antarctica",
    subregion: "",
    population: 200,
    area: 1650000,
    currencies: ["GBP"],
    languages: ["eng"],
    latlng: [-80, -40],
    flag: "https://flagcdn.com/w320/aq.png"
  },

  // 🌏 Asia
  {
    name: "India",
    nativeName: "भारत",
    cca2: "IN",
    cca3: "IND",
    continentCode: "AS",
    continent: "Asia",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
    population: 1412160000,
    area: 3287263,
    currencies: ["INR"],
    languages: ["hin", "eng"],
    latlng: [20.5937, 78.9629],
    flag: "https://flagcdn.com/w320/in.png"
  },
  {
    name: "China",
    nativeName: "中国",
    cca2: "CN",
    cca3: "CHN",
    continentCode: "AS",
    continent: "Asia",
    capital: "Beijing",
    region: "Asia",
    subregion: "Eastern Asia",
    population: 1412600000,
    area: 9596961,
    currencies: ["CNY"],
    languages: ["cmn"],
    latlng: [35, 105],
    flag: "https://flagcdn.com/w320/cn.png"
  },
  {
    name: "Japan",
    nativeName: "日本",
    cca2: "JP",
    cca3: "JPN",
    continentCode: "AS",
    continent: "Asia",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
    population: 125960000,
    area: 377975,
    currencies: ["JPY"],
    languages: ["jpn"],
    latlng: [36, 138],
    flag: "https://flagcdn.com/w320/jp.png"
  },
  {
    name: "Indonesia",
    nativeName: "Indonesia",
    cca2: "ID",
    cca3: "IDN",
    continentCode: "AS",
    continent: "Asia",
    capital: "Jakarta",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 273523615,
    area: 1904569,
    currencies: ["IDR"],
    languages: ["ind"],
    latlng: [-5, 120],
    flag: "https://flagcdn.com/w320/id.png"
  },
  {
    name: "Saudi Arabia",
    nativeName: "المملكة العربية السعودية",
    cca2: "SA",
    cca3: "SAU",
    continentCode: "AS",
    continent: "Asia",
    capital: "Riyadh",
    region: "Asia",
    subregion: "Western Asia",
    population: 34813871,
    area: 2149690,
    currencies: ["SAR"],
    languages: ["ara"],
    latlng: [25, 45],
    flag: "https://flagcdn.com/w320/sa.png"
  },
  {
    name: "Iran",
    nativeName: "ایران",
    cca2: "IR",
    cca3: "IRN",
    continentCode: "AS",
    continent: "Asia",
    capital: "Tehran",
    region: "Asia",
    subregion: "Southern Asia",
    population: 83992949,
    area: 1648195,
    currencies: ["IRR"],
    languages: ["fas"],
    latlng: [32, 53],
    flag: "https://flagcdn.com/w320/ir.png"
  },
  {
    name: "Thailand",
    nativeName: "ประเทศไทย",
    cca2: "TH",
    cca3: "THA",
    continentCode: "AS",
    continent: "Asia",
    capital: "Bangkok",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 69799978,
    area: 513120,
    currencies: ["THB"],
    languages: ["tha"],
    latlng: [15, 100],
    flag: "https://flagcdn.com/w320/th.png"
  },
  {
    name: "Vietnam",
    nativeName: "Việt Nam",
    cca2: "VN",
    cca3: "VNM",
    continentCode: "AS",
    continent: "Asia",
    capital: "Hanoi",
    region: "Asia",
    subregion: "South-Eastern Asia",
    population: 97338579,
    area: 331212,
    currencies: ["VND"],
    languages: ["vie"],
    latlng: [16, 108],
    flag: "https://flagcdn.com/w320/vn.png"
  },
  {
    name: "Pakistan",
    nativeName: "پاکستان",
    cca2: "PK",
    cca3: "PAK",
    continentCode: "AS",
    continent: "Asia",
    capital: "Islamabad",
    region: "Asia",
    subregion: "Southern Asia",
    population: 231402117,
    area: 881912,
    currencies: ["PKR"],
    languages: ["urd", "eng"],
    latlng: [30, 70],
    flag: "https://flagcdn.com/w320/pk.png"
  },
  {
    name: "South Korea",
    nativeName: "대한민국",
    cca2: "KR",
    cca3: "KOR",
    continentCode: "AS",
    continent: "Asia",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
    population: 51780579,
    area: 100210,
    currencies: ["KRW"],
    languages: ["kor"],
    latlng: [37, 127.5],
    flag: "https://flagcdn.com/w320/kr.png"
  }
];
